### PR TITLE
Add copy task for static files

### PR DESCRIPTION
**Pull request by nicolaisueper**
Add task for copying static files to `libs/` directory

### CODE REVIEW

**Comment by mischah** [comment]
Build is red. Linting errors. You should start running `gulp` when developing 😏

**Comment by nicolaisueper** [comment]
Oh! Sorry, I'll fix this now

**Comment by nicolaisueper** [comment]
I'll never use code reformat before pushing again 😆

**Comment by mischah** [comment]
👍

**Pull request merged**
